//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SakaryaBufe
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cikolatalar
    {
        public int id { get; set; }
        public int kategoriId { get; set; }
        public string Baslik { get; set; }
        public string Aciklama { get; set; }
        public string Resim { get; set; }
        public string Fiyat { get; set; }
    
        public virtual Kategoriler Kategoriler { get; set; }
    }
}
